version: '3.4'

services:
  myshop.api:
    image: ${DOCKER_REGISTRY-}myshopapi
    build:
      context: .
      dockerfile: MyShop.API/Dockerfile

  myshop.worker:
    image: ${DOCKER_REGISTRY-}myshopworker
    build:
      context: .
      dockerfile: MyShop.Worker/Dockerfile

networks:
  default:
    external:
      name: kafka-broker_default